import { Inter } from "next/font/google";
import "./globals.css";

import HeroSection from "@/components/home/homeComponents/hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Optimenu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeroSection />
        {children}
      </body>
    </html>
  );
}
